### ISSUE TITLE
4.2 targets

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#101]
- explore race condition at endStudy (see Kamyar, TAAR)
- rename / simplify ping sending (sendEnterPing and friends)
- require variation for setup to eliminate setVariation
- logging
- handle normandy uninstall as a special thing

**Comment by motin** [comment]
Suggestion regarding logging: implement it in the same way as pioneerUtils: https://github.com/mozilla/pioneer-utils/blob/master/src/PioneerUtils.ts#L306

**Comment by motin** [comment]
Suggestion: Target v5 instead of 4.2

**Comment by motin** [comment]
Closing since the relevant ideas now have their own issues for discussion and tracking:

- explore race condition at endStudy (see Kamyar, TAAR) - https://github.com/mozilla/shield-studies-addon-utils/issues/146
- rename / simplify ping sending (sendEnterPing and friends) - https://github.com/mozilla/shield-studies-addon-utils/issues/145
- require variation for setup to eliminate setVariation - https://github.com/mozilla/shield-studies-addon-utils/issues/147
- logging - https://github.com/mozilla/shield-studies-addon-utils/issues/139
- handle normandy uninstall as a special thing - https://github.com/mozilla/shield-studies-addon-utils/issues/148
