### ISSUE TITLE
v5 Documentation, including readme

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#126]
- [ ] where to host docs

**Comment by motin** [comment]
>  where to host docs

I suggest that for v5, the docs are hosted in Github, ie part of the repository. We can have an ambition to move all docs to a separate system for v6?

**Comment by motin** [comment]
Let's make sure that this issue deprecates https://github.com/mozilla/shield-studies-addon-utils/issues/93

**Comment by motin** [comment]
Closing this issue in favor of https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments, which since https://github.com/mozilla/shield-studies-addon-utils/commit/034eb87d00d87d0a54bb804e67415f92c2422c19 (which also cleaned up the readme) has been included as the go-to document for study add-on documentation.
