### ISSUE TITLE
Merge ideas from Pioneer Utils

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#128]

**Comment by motin** [comment]
As proposed in https://github.com/mozilla/shield-studies-addon-utils/issues/114, there are two ways to accomplish this:

* Add pioneer-utils as a dependency to shield-studies-addon-utils and let the studies experimental API take care of choosing the appropriate API methods of shield-studies-addon-utils and/or pioneer-utils depending on add-on configuration (Pioneer or not)
AND/OR
* Merge pioneer-utils functionality into shield-studies-addon-utils - [Request to merge / unfork: Shield-Studies-Addon-Utils #25](https://github.com/mozilla/pioneer-utils/issues/25)

Since tests are not yet written for pioneer-utils, I suggest that we start off with the first option, and later do a complete merge.

**Comment by motin** [comment]
We also need https://github.com/mozilla/shield-studies-addon-utils/issues/142 implemented
