### ISSUE TITLE
Can we / should we switch to telemetry events.  If so how?

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#130]

**Comment by gregglind** [comment]
Related to #122 

Questions:  
1.  Is ANYONE using the shield-studies, shield-studies-addon events?
2.  How are we tracking the people in a study?

**Comment by motin** [comment]
1. Yes
2. Via [stmo](https://sql.telemetry.mozilla.org) - Example dashboard: https://sql.telemetry.mozilla.org/dashboard/taar-experiment-v2

**Comment by biancadanforth** [comment]
@raymak and I met with Sunah and Georg this morning. We both agree that moving to Event Telemetry would be best. Whether that's a v5 milestone or not is another matter.

Kamyar, you could probably explain the takeaways from that meeting better than I can. Could you share them here?

**Comment by raymak** [comment]
My thoughts on the meeting we had with Sunah and Georg:

 - Use of Event Telemetry is preferred by them as it would be easier to support one data collection model rather than many
- Event Telemetry is still in its early stages and they have plans to expand its capabilities such as automated summarization and analysis

Pros
- we get better support from the data pipeline team
- we get the extra tools the data pipeline teams is going to build for free
- as a customer, we could voice our needs for further development of Event Telemetry
- the schema of the pings has to be defined to some extent at runtime, which forces developers to be more principled with their data collection

Cons
- the format is more generic than the existing ping format that we have, and the data collected will not have as nice a hierarchical structure as we currently have. See the example below:

- although they have plans to do it, association of experiment branches and installed addons with the pings has not completely been established. See the example below:

__existing study ping payload__
```
{
  "branch": "private",
  "study_name": "addon-tracking-protection-messaging-1433473-all-users",
  "addon_version": "1.0.1",
  "version": "3",
  "study_state": "installed"
}
```

__new study ping payload__
```
[2147, "shield", "state_change", "addon-tracking-protection-messaging-1433473-all-users", "installed", {"branch": "private", "addon_version": "1.0.1", "version":"4"}]
```

__existing addon ping payload__
```
{
  "branch": "private",
  "study_name": "addon-tracking-protection-messaging-1433473-all-users",
  "addon_version": "1.0.1",
  "version": "3",
  "study_state": "installed",
  "attributes": {
     "message_type": "event",
     "event": "panel-shown",
     "panel_type": "intro-panel",
  }
}
```

__new addon ping payload__
```
[2147, "shield_addon", "event", "addon-tracking-protection-messaging-1433473-all-users", "panel-shown", {"panel_type": "intro-panel", "branch": "private", "addon_version": "1.0.1", "version":"4"} ]
```
Of course there are other ways to convert the existing ping format into the new Telemetry Event format, but none will be perfect.

My recommendation:

Less work => it does not seem to me that we would be getting the killer capabilities of Event Telemetry (e.g. automated summarization) in the near future. Therefore, I think it would be best to stick with the existing pipeline for study pings. For addon pings, we could continue the support for the existing pipeline, while leaving it up to the discretion of the addon developer if they want to use either method (e.g. project Savant).

More work => support the existing pipeline as well a duplicate ping in the Event Telemetry pipeline and see how it will turn out in the future. This should not be much work actually. So overall, this is my top recommendation.

More info: https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/collection/events.html

**Comment by motin** [comment]
Formatted new ping payloads from comment above:

```
[
  2147,
  "shield",
  "state_change",
  "addon-tracking-protection-messaging-1433473-all-users",
  "installed",
  {
    "branch": "private",
    "addon_version": "1.0.1",
    "version": "4"
  }
]
```

```
[
  2147,
  "shield_addon",
  "event",
  "addon-tracking-protection-messaging-1433473-all-users",
  "panel-shown",
  {
    "panel_type": "intro-panel",
    "branch": "private",
    "addon_version": "1.0.1",
    "version": "4"
  }
]
```

I find the existing payloads self-explanatory, but the new payloads requires a bit more clarification - @raymak could you link to the schemas defining the new payloads?

When it comes to implementation and timeline, we can [make utils supporting different pipelines](https://github.com/mozilla/shield-studies-addon-utils/issues/130) and thus keep supporting the existing pipeline while adding experimental support for custom telemetry events.

**Comment by motin** [comment]
Related: https://github.com/mozilla/shield-studies-addon-utils/issues/164

**Comment by motin** [comment]
Closing this since the emergent answer is: Yes, we should and it should be done by following relevant docs and #164
