### ISSUE TITLE
[v5] [develop]  Switch to TypeScript or other argument guarding system?

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#140]
@Osmose @rehandalal 

Issue:  type checking and guarding in JS is terrible.  

Should we switch TypeScript?  Something else?  I am agnostic, if it's low cost.

**Comment by motin** [comment]
Related: https://github.com/mozilla/shield-studies-addon-utils/issues/138

**Comment by rehandalal** [comment]
We have actually been hit in the past by some issues that would have been caught by strict type checking and that's why @mythmon rewrote pioneer-utils in typescript. We never did end up using the typescript version because we didn't have the bandwidth to write tests, but this idea has come up before and we thought it was worth going down the road then so chances are --- that is still true.

**Comment by gregglind** [comment]
Currently:  use a lot of JSON guarding.  It's good enough but very very fragile with Ajv versions.
