### ISSUE TITLE
V5 must support cloudStorage

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#173]
- studyInfo () => is correct, and has expires
- studySetup () => works correctly every run
- (new) uninstall () => becuase you can’t do it from the addon
- onEndStudy
- onStudyReady
- sendTelemetry
- getInfo()

**Comment by gregglind** [comment]
@rhelmer, from here is where I am going to be landing code that needs the review.  

So far
- webExtension Experiment API
- yes to linting, prettify
- yes to selenium / webdriver
- no to mochitest, and I have *no idea* of how to do that
- no to talos perf and I have *no idea* of how to do that.

**Comment by rhelmer** [comment]
>  webExtension Experiment API
>   yes to linting, prettify
>   yes to selenium / webdriver

sgtm

>   no to mochitest, and I have no idea of how to do that
>   no to talos perf and I have no idea of how to do that.

@biancadanforth and I were just discussing this today... we are working with Mozilla infra folks to make this pretty seamless.

We're also going to look into the feasibility of running more standard test frameworks like Mocha, I don't think there's much point in writing mochitests that specifically test study code.

It's not all fleshed out yet, but the back-of-napkin sketch so far with regard to test integration is something like this:

1) opening a PR causes a travis/circle/something run, which runs any study-specific code using mocha and linting and such, and also downloads firefox and runs a basic subset of the test suite
2) less frequently (maybe on merge to master?) a taskcluster job that runs on real mozilla infra will be kicked off. This will run correctness (function/integration, unit, and perf tests) with the shield study installed to assess how the study impacts any existing Firefox features and performance.

We hope that this will make it unnecessary for shield study authors to have to interact much with the Mozilla-specific test harnesses and infrastructure - the exception is going to be if we need to dig in to understand why some Firefox test is failing, but this should be the exception rather than the rule.

I also expect that as we build a well-tested set of experimental webextension APIs, we'll compartmentalize this sort of work there and individual study authors will be writing pure webextension code that may use these experimental APIs, and won't necessarily be solely responsible for tracking down anomalies.

**Comment by motin** [comment]
This was inaccurately closed by Github logic. Re-opening.

**Comment by motin** [comment]
@punamdahiya How is the CloudStorage add-on doing in QA with regard to utils? Let us know if there are still issues that requires changes to utils or if this issue (#173) can be considered closed :)

**Comment by motin** [comment]
Answering me own question, I found "From the QA point of view the add-on is ready to be released to end users." on https://bugzilla.mozilla.org/show_bug.cgi?id=1441949#c29 and thus conclude that the add-on has passed QA using utils v5.0.2
