### ISSUE TITLE
"Better Study Endings" Engineering Plan (Proposed)

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#246]
# "Better Study Endings" Engineering Plan (Proposed)

revision: 1.  (2018 jun 12)

compiled from discussions in #244 #232 #230 #231 #208 #206 #205 #194 #188 #179 #148 

## Principles:

1.  Studies are packaged as addons, but are not addons. Studies have different ending semantics and expectations than usual addon patterns.  (No "re-enable", no "undo" see #230).
2.  Studies are WebExtensionExperiments, which means they have full privileged power.  The `shield-studies-addon-utils` can interact with Firefox modules "behind the scenes"
3.  Studies are written by trusted authors.  Study Authors will not intentionally abuse Firefox users.  Trust means they can have different tools than usual addon authors.

### Preserve desired ending behaviour for Studies:

  1.  Allow users to leave studies
  2.  Reliably detect user intent to remove a Study-implemented feature.
  3.  For a study, distinguish 'Normandy rollback' from 'user intent to remove'.  Ensure telemetry for each is different.  Normandy revoke happens to correct bugs, or mis-targeting, and should not reflect badly on a study.  "User opt-out" should penalize that variation of a study.
  4.  For *all* study endings, give the addon time to do all shutdown / cleanup and final telemetry procedures.

### WebExtension Engineering goals

As a **study engineer**, I want to:

1.  Allow addons to centralize all study ending handling in one function in the webExtension space at `browser.study.onEndStudy`

### Firefox Extensions goals

As Firefox engineering Extensions module owner, I want to:

1.  Continue to treat general addons (webExtensions) with distrust.  Do not block on uninstall, or hang the thread.
2.  Support these in a way that doesn't require huge changes in Firefox.

### QA Goals:

As a Study QA person, I want to:

1.  Have predicable, reliable Study ending behaviour.
2. Be able to trigger endings artificially to check handling

## Current State:

1.  Both "user intent" and "normandy revoke" use the usuall `addon.uninstall()`.  The addon cannot distinguish these for purposes of surveys and telemetry.  
2.  `addon.uninstall()` signals for `ADDON_UNINSTALL` do not propagate into the 'getAPI' or the webExtension code.  

#### Mechanism ideas:
1.  Have a manifest.json flag called "study: true", or "hidden: true' that is *only* respected for mozilla signed addons.  
2.  Filter on id regex '@(pioneer|shield).mozilla.org'

(1 is more work but safer from malicious actors).

#### Code changes:
1.  Implement the filtering in `about:addons`, including the regex, signing check etc.
2.  consider a pane / link to `about:studies` to deal with user unclarity.
3.  ensure `about:support` has a listing for SUMO use.

#### Reasoning:  The 'warning' lets the addon do these:

a. know which reason (normandy, vs user intent)
b. have (some) time to shutdown.

#### Mechanism ideas:
1.  In Normandy code, and in `about:studies`, change from `addon.uninstall` to:

    - warn using [`nsiObserverService`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIObserverService)
    - setTimeout for 5 seconds
    - then do `AddonManager.getAddonByID(id, addon => addon.uninstall())`

#### Code changes needed:

1.  In Normandy's revoke mechanism, implement the 'warn then uninstall'
2.  In `about:studies` revoke mechanism,

    - implement the 'warn then uninstall'.
    - change ui to relfect this in the button state.  (ie., an "uninstalling..." state)

3.  In `shield-studies-addon-utils`, 

  - implement the Listener for the `nsiObserverService` message.  Trigger `endStudy` so that `onEndStudy` propogates.
  - (good side effect:  this also allows QA / devs to trigger endings)

### Unclear aspects, with opinions:

1.  Should study addons appear in telemetry under addons?  I claim for now, yes.  This is 'no change'.  
2.  How to filter out of `about:addons`.  I am not sure if all studies will be mozilla-signed.  I *think* that is a safe constraint.
3.  Exact call to `nsiObserverService`.  My naive suggestion is:

    ```
    subject:  study-revoke  | about-studies-user-disable 
    topic:  [addonId for the addon]
    ```
4.  How long to wait.  I claim even 5 seconds would be enough for most studies.  They may need to open a few tabs.  The 'longest' scenario is if they have to send a final ping that relies an expensive calculation over history / all tabs.  If so, it is up to the study to make that calculation incremental / cheaper.  

## Proposed solution 2:  Super smart Normandy

In addition to the 'hide studies' part, we could make normandy handle *much more* of the telemetry.  

I claim this requires a lot more thought, and reevalution of the what a study addon is. I claim this is too big, and that all the changes in solution 1 are on the path to this plan.

I claim also that this plan has a lot of benefits for QA-ing individual studies being simpler.

I suggest that we punt on this a month or two to think.  

## Edge cases

- addons are weird.  People can still uninstall by removing the addon from a profile while Firefox is not running.
- possible that people will not be able to discover studies, and be annoyed. 
- there is no amount of time that guarantees 

## Comments Wanted

My claim is that proposal 1 is reasonable, and addresses most problems around endings.

@raymak @biancadanforth @pdehaan @aswan @rhelmer

## Timeline:

- ASAP because this rides the trains.  @aswan?  
- changes to `shield-studies-addon-utils   would take 3 days to write and qa.  Shield team does this.

**Comment by ddurst** [comment]
Let's not do this via a plethora of issues filed (and filing new ones); it's just going to get more confusing. If this is summarizing everything else, let's close everything else, and discuss this in a a real-time meeting after the Web Extensions team gets a chance to review and plan.

**Comment by gregglind** [comment]
I am fine with that.  I will close them all.

**Comment by ddurst** [comment]
(But: thank you for summarizing, because <whew> that was getting complicated.)

**Comment by aswan** [comment]
Just chatted with @gregglind about this for a while.  I think this proposal seems good, my only suggestion is that we make `onEndStudy` listeners return a Promise, and then uninstall the extension after that Promise resolves, rather than using a fixed timer.  I'm happy to help with the implementation of that.
There are a bunch of moving pieces here, it looks like we need changes to at least:
- AddonManager
- Normandy
- shield-studies-utils

The first two need to ride the trains, if we get them done in the next few weeks we'll have them in 63.

**Comment by aswan** [comment]
Just chatted with @gregglind about this for a while.  I think this proposal seems good, my only suggestion is that we make `onEndStudy` listeners return a Promise, and then uninstall the extension after that Promise resolves, rather than using a fixed timer.  I'm happy to help with the implementation of that.
There are a bunch of moving pieces here, it looks like we need changes to at least:
- AddonManager
- Normandy
- shield-studies-utils

The first two need to ride the trains, if we get them done in the next few weeks we'll have them in 63.

**Comment by motin** [comment]
> The first two need to ride the trains, if we get them done in the next few weeks we'll have them in 63.

That would be great! Who is assigned to make this happen in time? :)

**Comment by aswan** [comment]
We have bug 1365349 for the AddonManager bits, I don't know about the Normandy part.

**Comment by aswan** [comment]
Filed for the Normandy portion:
https://bugzilla.mozilla.org/show_bug.cgi?id=1481918

**Comment by motin** [comment]
@gregglind What is the current status and implementation plan for this? I have gathered from various sources that since Firefox 63, better study endings are "possible", and that `hidden: true` in the manifest to hide study add-ons from `about:addons` is available for signed add-ons. 

There is one current implementation issues related to this: https://github.com/mozilla/shield-studies-addon-utils/issues/267 - but it only concerns updated handling of the endings, it does not concern nor explain how the development process from a study add-on engineer's perspective. It doesn't mention the use of `hidden: true`.

If we use `hidden: true`, will we be able to verify the correct behavior also for unsigned add-ons, or wWill we and QA need to use Normandy devtools in order to install and uninstall studies in order to validate correct expiration and end-study behavior?

I am sensing that all of this is very close to being available to study add-on engineers, only a proper utils patch and corresponding docs are missing?

**Comment by motin** [comment]
Quick update on the current state of this:

Most of the proposed changes have been implemented except those related to study utils. 

As before, the privileged portion of the code does not receive any event upon expiration since it is handled in webextension land by shield study utils. 

To handle the expiration, study add-ons should make sure to listen to the "onEndStudy" event, which only exists in the non-privileged part of the add-on. see https://github.com/mozilla/shield-studies-addon-template/blob/master/src/background.js# L49 and https://github.com/mozilla/shield-studies-addon-template/blob/master/src/background.js#L121 for a working example of uninstallation upon expiry. 

Until this issue (issue 246) is resolved, the onEndStudy event will only trigger for expiration, ie not when Normandy uninstalls the add-on, for which study add-ons need to 
listen to the Normandy unenrollment event using something like the following in the privileged portion of the add-on:
```
const {AddonStudies} = ChromeUtils.import("resource://normandy/lib/AddonStudies.jsm", {});
AddonStudies.addUnenrollListener(this.extension.id,
+                                                     reason => {/* clean up and uninstall the add-on here */});
```

Making onEndStudy fire upon Normandy unenrollment, and making sure that a Promise is returned and resolves only when onEndStudy is finished executing is what we need to bake into study utils in order to close this issue. Only then will study add-ons not have to implement the Normandy unenroll listeners themselves.
