### ISSUE TITLE
when Shield removes the study addon in the context of an opt-out study, it looks like the user has disabled it

### ISSUE THREAD

**Issue by raymak** [mozilla/shield-studies-addon-utils#89]

**Comment by raymak** [comment]
Two possible solutions:
- the Shield client addon sets a pref before killing the study addon, and the study addon reads it upon uninstall
- use the global notification observer

**Comment by jtg567** [comment]
If this is happening in the context of a study that ends without a user reaching a final exit state on their own, it would be more valid for analysis for their final exit state to be an "expire" rather than "user_disable."

Otherwise we risk over-estimating/reporting rates of self-removal from studies.

**Comment by motin** [comment]
Closing this since Normandy support for this has been added in Firefox 63: https://bugzilla.mozilla.org/show_bug.cgi?id=1481918 and will be incorporated into the utils via https://github.com/mozilla/shield-studies-addon-utils/issues/246
