### ISSUE TITLE
DOCS, WIP, FAQ

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#93]
## What is the current `best practices` template.

As of 2017-11-16:
http://github.com/mozilla/shield-studies-addon-template

~~As of 2017-10-03:
http://github.com/gregglind/template-shield-study~~

## Useful LEGACY ADDON building links.

*LEGACY ADDON* contrasts with "extension" or "addon" which are now **webextensions**.  Legacy Addon is the term for the `bootstrap.js` with a `startup` method way of doing things.

- Globals that are defined in `bootstrap.js`, including `__SCRIPT_URI_SPEC__` at https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIProvider.jsm#4335-4353
- https://developer.mozilla.org/en-US/Add-ons/Legacy_add_ons
- https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/XPCOMUtils.jsm#defineLazyModuleGetter()

## Explain `resource` files and `chrome.manifest`

`resource://` maps a FILE SYSTEM list of files, using the ALIASES in a `chrome.manifest` file.

Example line in `chrome.manifest`

```resource some-addon-name .```

and this folder structure
```
$ tree addon
addon
├── Config.jsm
├── StudyUtils.jsm
├── bootstrap.js
├── chrome.manifest
├── install.rdf
├── lib
│   ├── AddonPrefs.jsm
│   └── Feature.jsm
└── skin
    └── heartbeat-icon.svg
```

THEN, that `chrome.manifest` maps these paths between the `resource` protocol and the `jar` protocol.

```resource://some-addon-name/skin/heartbeat-icon.svg  ==> jar:///abs/path/to/theAddon.xpi!/skin/heartbeat-icon.svg```

WARNINGS:
1.  The characters @ # ; : ? / are not allowed in the `alias`.  This is annoying, because it means you can't use your `addonId` as the `alias`
2.  Resource files  won't show up in dev tools `debugger` until you attempt to import / use them.
3.  If two addons use the same `alias`, I have no idea of what will happen, but it's PROBABLY BAD.  Your alias should be unique to your addon.
4.  `chrome.manifest` resource paths aren't loadable until LEGACY `startup`.  In particular, they are NOT usable during `install`.  

## All about LEGACY (Bootstrap / Restartless) addons.

https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions

## Is Firefox Wack?

Yes.  In particular, LEGACY ADDONS (`bootstrap`) addons are an orphaned technology, that we still need to use.  Debugging is hard.  `Cu.import` is NOT `require`.

## How do I debug?

- `about:debugging`, does `load temporary addon`, `reload` (which won't work if you changed things!) and uninstall.
- `tools > web developer > Browser Toolbox` (shift alt command i) shows ALL BROWSER LOGGING, which might be where your addon things go.  In particular, if you have thrown errors in your bootstrap or other files.
- `about:telemetry` records all 'current' and 'archive' Telemetry Pings.

## when to use `isEligible` as part of `install` 

From gregglind/57-perception-study#3 
```I noticed isEligible just returns true -- when would we use this method versus using filter expressions in Normandy?```

Reasons
1. JEXL expresssions inadequate.  Normandy controls who is offered the study.  The JEXL elements it can select on might be inadequate for expressing this criteria.
2. Changes during install.  It's a 'backstop' (belt and suspenders) in case the user changes during the download process.
3.  If the same study is distributed other ways, beside Normandy.

## Writing Tests

Answer: https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox/index.html

## I am having a sadness.

Me too buddy.  Me too.

## SIGNING

As of 57 (2017-10-05), to get a LEGACY addon to work with BETA or RELEASE, **it must be signed with the special legacy signing key**, EVEN IF you `about:debugging > load temporary addon`.

Solutions (in brief)
- use Nightly
- use unbranded Firefox
- get a signed addon.   

### Initial signing flow
- NAME your addon like this:  `<addonId>-<version>.xpi`
- upload the addon somewhere (such as s3 / Google drive)
- use this [bugzilla signing bug template](https://bugzilla.mozilla.org/enter_bug.cgi?assigned_to=mcooper%40mozilla.com&bug_file_loc=http%3A%2F%2F&bug_ignored=0&bug_severity=normal&bug_status=NEW&cf_fx_iteration=---&cf_fx_points=---&cf_status_firefox56=---&cf_status_firefox57=---&cf_status_firefox58=---&cf_tracking_firefox56=---&cf_tracking_firefox57=---&cf_tracking_firefox58=---&comment=Reason%20for%20signing%0D%0A%0D%0ATEST%20TEST%20TEST%20TEST%20TEST%20TEST&component=Shield%20Study&contenttypemethod=autodetect&contenttypeselection=text%2Fplain&defined_groups=1&flag_type-4=X&flag_type-607=X&flag_type-800=X&flag_type-803=X&flag_type-916=X&form_name=enter_bug&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=Unspecified&priority=--&product=Shield&rep_platform=Unspecified&short_desc=Sign%20XPI%20for%20STUDY%20NAME%20HERE&target_milestone=---&version=unspecified)
- get signed addon as an attachement.

See example:  
- https://bugzilla.mozilla.org/show_bug.cgi?id=1407757

## Tracking and Debugging Telemetry Pings

There is an addon for that!  It makes reports.

- https://bugzilla.mozilla.org/attachment.cgi?id=8917534

**Comment by biancadanforth** [comment]
### How do I debug
Perhaps mention that if you use the addon debugger, the only script that logs to the addon debugger console is `bootstrap.js`. Otherwise you have to look in the browser console, where every script running in the browser dumps logs, warnings and errors. There might be a way to bundle all the modules into a single script file; I guess it'd have to be called `bootstrap.js`... Something I'd like to look into.

### When to use isEligible as part of install
Can you give an example or two of when you've had to use `isEligible` for each of the three reasons given?

### Writing Tests
Marc Robert Wong's [share-button-study](https://github.com/mozilla/share-button-study) is the best example of Selenium Webdriver/Geckodriver at work on a bootstrapped addon. Can we point people to this here and say what all he has been able to automate?

**Comment by gregglind** [comment]
## Icons in Legacy Addons

So you want to have 'top level' icon your addon?

```
# chrome.manifest
content qa-shield-study-helper-icons ./somepath/
```

install.rdf
```
    <em:iconURL>chrome://qa-shield-study-helper-icons/content/icon.png</em:iconURL>
```
NOTE the `content` in the url, and the `chrome` as the protocol.  These are unexpected.

**Comment by biancadanforth** [comment]
Feedback from [mostly] Kamyar's and my experience building [this shield study](https://github.com/raymak/cfr-focused-beta):

Template improvements
* Testing the study using `npm run firefox` should work for all OSes, not just Mac. Perhaps write a script that detects OS and makes necessary changes?
  * Ubuntu: This is trivial to get it to work (just change the `FIREFOX_BINARY` environment variable in `package.json` to either `/usr/bin/firefox` or `/usr/bin/firefox-trunk`).
  * Windows: I have spent the better part of this morning getting it to work to no avail. Known changes: replace `export` with `set` in the `firefox` command in `package.json`. Change `FIREFOX_BINARY` value, but to what? I have tried: `C:\\Program Files\\Nightly\\firefox` and it [fails](https://github.com/raymak/cfr-focused-beta/blob/dfb01355ad6eb3d355a15197c6c2008b5f53e3e9/test/utils.js#L39) with ENOENT.
* Have a tool (possibly using Firefox GCLI?) to debug/reconfigure/reset study code in real time. @raymak has a lot of ideas about this.

UI capability improvements
* Make it possible to flexibly size UI elements so their dimensions do not have to be hardcoded by OS.
  * For the notification bar and panel/doorhanger element, different OSes display them slightly differently (likely due to system fonts?).
  * Look into the `flex` attribute for XUL elements.
* Be able to display a custom dropdown menu correctly *overlaid over webpage content* (rather than shifting down, and preferably using HTML, not XUL) that expands past the original notification bar height.

**Comment by biancadanforth** [comment]
### Draft QA Review Process

This is based on feedback from Gregg's experience reviewing the [57-perception-study](https://github.com/gregglind/57-perception-shield-study).

**Shield Team Deliverables pre-QA:**
- A [bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1406537) for the study that can be referenced by QA.
  - With a signed XPI attached for installation of the addon.
- A [README.md](https://github.com/mozilla/pioneer-enrollment-study/) which describes on a high level what the study is looking at, possibly also listing all the different UI treatments, experimental branches, custom prefs and what they represent.
  - Note: The example README above combines readme, test plan and telemetry documentation into one. We would like to break this out.
- A [TESTPLAN.md](https://github.com/gregglind/57-perception-shield-study/blob/master/TESTPLAN.md) which describes how to install the addon, what manual tests to perform and how to perform them -- ideally with screenshots/a gif of what it looks like.
  - What QA can test:
    - Install addon
    - Make new profile(s)
    - Set preferences
    - Try locales
    - run Firefox on different platforms (ex: Windows)
    - Check for: security, performance, functional and display issues.
    - If telemetry pings are correct, if and only if we provide them with the right tool (see TELEMETRY.md below). *TODO @gregglind , please send me the link to your helper addon!*
- A [TELEMETRY.md](https://github.com/gregglind/57-perception-shield-study/blob/master/TELEMETRY.md) which describes what telemetry pings are expected and when.

**QA Deliverables to Shield team after testing**
- A list of issues/tests, flagged by priority (ex: critical blocker or nit), marked as passed or failed.
  - Included in this list is anything QA finds valuable that may not have been part of the list of tests.

**Comment by gregglind** [comment]
- Link to the wiki for PROCESS stuff, mostly
- get best of "how to shield study"
- get shield-studies-docs for the rest of the best stuff.

consider doing readthedocs?

**Comment by gregglind** [comment]
https://hacks.mozilla.org/2017/07/introducing-sphinx-js-a-better-way-to-document-large-javascript-projects/

**Comment by gregglind** [comment]
https://github.com/mozilla/pioneer-studies-addon-utils/pull/4

**Comment by biancadanforth** [comment]
@motin Did a great job updating the [Readme/repo](https://github.com/gregglind/template-shield-study) for the template shield study.

We can improve on this by including the `npm run firefox` command as a semi-automated alternative to manually loading the temporary add-on every time. Ideally the `watch` command could be integrated into the `firefox` command, so that when the code changes, not only is a new XPI built, but Firefox is launched in a new profile with various prefs and the addon already loaded.
Consider also making Selenium Webdriver open `about:config` on starting up Firefox?

**Comment by motin** [comment]
@biancadanforth 
> We can improve on this by including the npm run firefox command as a semi-automated alternative to manually loading the temporary add-on every time.

Available https://github.com/gregglind/template-shield-study/pull/15/commits/02c52b5b873117fab6faae6ec9b8a543c1890ae5 as part of https://github.com/gregglind/template-shield-study/pull/15

> Ideally the watch command could be integrated into the firefox command

Created a related issue: https://github.com/gregglind/template-shield-study/issues/16

> Consider also making Selenium Webdriver open about:config on starting up Firefox?

Greg's latest changes makes about:debugging open on startup. Additionally, [the browser console ought to open automatically](https://github.com/gregglind/template-shield-study/pull/6) imo

**Comment by gregglind** [comment]
QA helper addon

https://bugzilla.mozilla.org/show_bug.cgi?id=1407757

**Comment by motin** [comment]
Up to date (Oct 24) Telemetry notes from a recent meeting with Georg, the owner of the Telemetry component at Mozilla: https://docs.google.com/document/d/1fzl6bieNkMGQgJUMXl83pDcdBH_ncQuprOsVqN_i2Qo/edit

**Comment by motin** [comment]
@gregglind Two questions which I am missing answers to from docs: 
1. Is it ok to use console.log in the final add-on, or should shield-specific logging be used?
2. Are exceptions caught by shield utils and reported properly, or does each add-on need to catch their exceptions and for instance send an exception-ping with details about the error?

**Comment by motin** [comment]
@gregglind, update the current best practice template url in the issue description :) https://github.com/mozilla/shield-studies-addon-template/issues/16

**Comment by motin** [comment]
This Google doc is important to reference in docs: [How to ship a native study - i.e., implemented as add-on, Opt-in, Opt-out, or Pioneer](https://docs.google.com/document/d/1hOMjZ7l1K0HL8DUp7HCr8BeRO7NGw0SwYjK2nfwtRJQ/edit#heading=h.10dunphpi5if)

**Comment by motin** [comment]
@gregglind I got these questions, answering them here, FAQ style, so that the latest developments are included:

> Do you have a skeleton example for a prototype shield study?

The official template is more or less up to date with the latest stuff: https://github.com/mozilla/shield-studies-addon-template

Also check out https://github.com/motin/taar-experiment-v2-shield-study (work in progress)

> Also, what's the "state of the art" right now? Are we still doing legacy extension shield studies? Or are we doing webextension only?

We are moving away from legacy extensions to webextensions only but it will take a while before we are there. First steps involve defining the necessary extensions to the webextension API to be able to send telemetry, read/write preferences and other things that shield add-ons now requires legacy extension code to do. For more information, check out this google doc: [Removing Bootstrapped Extensions](https://docs.google.com/document/d/1ZilDLCiw7jArpE8MyB16S3EDmtxSdAR5h9-p0O7NzA0/edit#)

**Comment by motin** [comment]
Utils v5 has now landed in master, meaning that there should be no shield studies built as legacy extensions going forward

**Comment by motin** [comment]
Closing this issue in favor of https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments
